name:                valida
version:             1.0.0
github:              "TotallyNotChase/valida"
license:             MIT
author:              "Chase"
maintainer:          "totallynotchase42@gmail.com"
copyright:           "TotallyNotChase"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Simple applicative validation for product types, batteries included!
category:            Validation, Data

description:
    This package provides an applicative validator with support for contravariance. This makes building validators for product types idiomatic and simple. Many common utilities for building validators are also included.

dependencies:
- base >= 4.13 && < 5
- profunctors

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-uni-patterns
- -Wmissed-specialisations
- -Wmissing-export-lists
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
  - Valida
  - Valida.Combinators
  ghc-options:
  - -O2

tests:
  valida-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - tasty-smallcheck
    - smallcheck
    - valida
